default_velocity_scaling_vector: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 400.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_2:
    has_velocity_limits: true
    max_velocity: 670.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_3:
    has_velocity_limits: true
    max_velocity: 2400.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint_4:
    has_velocity_limits: true
    max_velocity: 2500.0
    has_acceleration_limits: true
    max_acceleration: 5.0